#!/usr/bin/env python
# -*- coding: utf-8 -*-


splash = """\
'                                                                      '
'                                        `.             ``             '
'                          `..--::::---/sh/-:::://++o+/:`              '
'                     .:+syhhhhhhhhhhhhhhh+yhhhhys/-`                  '
'                  -+yhhhhhhhhhhhhhhhhhhhsosyhhhhhhhyso:.              '
'         ````   -shhhhhhhhhhhhhhhhhhhhyh+hhshhhhhhhhhdNNmy+.          '
'     `-:/++////+yyysshhmdhhhhhhhhhhhhshy:shhyhhddmmmNNNNNNNNdo-       '
'  `-/+++//+/++++ooosddmNNNmmmdddhdddyshohosddmdmmmmmmmmmmmdhdddy:     '
'./++++/:/yy+++++/+yhhddhhhhhhhhyshhyhyshmshohhshhhhhhhhhhhhs..:+sy/   '
'-+++++//ys++++++/hhhhyhyyhhhhhhohhydyhsmmymhohyohhhhhhhhhhhhy:`  `-/. '
' :++++++y++++++/yhhhoyyyhhhhhy+yhydmssmmmdhmhoh/shhhhhyhhhhhhh+-`     '
'  :++++o++++++:yhhy+oyshhyssoooyydmdsdmmmmymmys+ooyyhhhshhhhhhh+:-    '
'   -++/s/++++/ohhy+/ysyyyyhshyhydmmyhmmmmmymmmoomsshhhhsshhhyyhh/.    '
'    `:/o+++++:hhs+o+sshhhhshmsydmmmhmmmmmmhmmmh+mmoyhhhyoshhhoyhy`    '
'      .+++++++hs/o+soyhhhohmhsmmmmmmmmmmmmdmmmm+mmmohhhh+oyhhy-oho    '
'      .+++++:yy//o/sshhhosys/yddmmmmmmmmmmmmmdhoooooohhhooshhh. :y-   '
'      :oo+hh+h/o/o/osho`/osso..-/hmmmmmmmmmms+:.-oh/oyhhsooyhh:  .+   '
'      :oo+hyo+oo/o/oshsoNNshd:::hmmmmmmmmmmmhdo::/Nhd+hhsooshh/   `   '
'      :oo+hy+/ood+++yyomdN::/:::ymmmmmmmmmmm+::::oNm+/yho/oshh+       '
'      :oo+yy+sosmoo/y+mmmN++y/+odmmmmmmmmmmm+s/osmNyyy+h++/oyh+       '
'      /oooohsyoodmo/osmmmmm++ssommmmmmmmmmmmhyhydNmsyo/h/o:-yh/       '
'      /ooo+yshyooyh//dmmmmmmmmmmmmmmmmmmmmmmmmmmmmd+/o/s:o- :h-       '
'      /oooo+yshsoooy+/oymdddmmmmmmmmmmmmmmmmmmmmddyo/oo-++.  +`       '
'      ++oooo+ohhsooshs+o:+hmmmmmmmmmmmmmmmmmmmmmhyoo/oo+o+`           '
'      ++ooooo+ohhsooyh+o/  ./sdmmmmmmmmmmmmhs+-+oooo/oooo/            '
'      ++oooooo/ohhsoshh+o.  :///yyyhhhsso-     ooooo/oooo:            '
'      ++ooooooo-+hhysshy++.////yhhhhhso///:.` `ooooo/ooos-            '
'      ++ooooooo: :hdysyhy+//////yhhhhhhs//////:++ooo/ooos-            '
'      +o+oooooo:  -ydhyyhs+://///ysyyyss://///:++o+o/ooos/            '
'      /o/oooooo: -o+yhhhhhs///////hhhhhh//////++oo/s/oooso            '
'      :o+ooooooodmy+/shhhhhs:+/////hhhhh////++o/y+sNsooosy            '
'      -oo/oooooNNNNms+shhhhho/o++++/hhhh/++oo++so+mNN+ooyh`           '
'      .oo+ooooyNNNNNNd+shhhhh+s+oooooNNN+ooo+oos+yNNNoooyh-           '
'                                                                      '"""